/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 duck/duck.glb -o src/components/Duck.jsx -r public 
Author: alfredonicolasalarcon (https://sketchfab.com/alfredonicolasalarcon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/duck-1ef90928c6994bb28d8069069dd5adce
Title: Duck
*/

import React, { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function DuckModel(props) {
  const { nodes, materials } = useGLTF('/models/duck/duck.glb')
  
  // Create a custom material with duck colors
  const duckMaterial = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      color: '#F5D547', // Golden yellow
      metalness: 0.2,
      roughness: 0.6,
      side: THREE.DoubleSide
    })
  }, [])
  
  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.Object_5.geometry} 
        material={duckMaterial}
        scale={0.01}
        castShadow
        receiveShadow
      />
    </group>
  )
}

useGLTF.preload('/models/duck/duck.glb')
